version: '3.8'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.1.3
    container_name: keycloak
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      KC_DB: postgres
      KC_DB_USERNAME: "${KEYCLOAK_POSTGRES_USER}"
      KC_DB_PASSWORD: "${KEYCLOAK_POSTGRES_PASSWORD}"
      KC_DB_URL: "jdbc:postgresql://${KEYCLOAK_POSTGRES_URL}"
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_PROXY_HEADERS: xforwarded
      KC_HTTP_ENABLED: true
    command: [ "start-dev" ]
    networks:
      - local-network
    volumes:
      - keycloak-data:/opt/keycloak/data

volumes:
  keycloak-data:
  
networks:
  local-network:
    driver: bridge